### ISSUE TITLE
Config value does not work for drop-down primitives

### ISSUE THREAD

**Issue by Toxantron** [PHOENIXCONTACT/MORYX-MaintenanceWeb#13]
**Describe the bug**
Configuration values like int or string, that have limited set of options should be displayed as a drop-down box, but are currently just text boxes.

**To Reproduce**
1. Define a primitive config value
2. Decorate with any type of PossibleValues (e.g. PrimitiveValues)
3. Open in configuration 
4. You will not see the expected drop-down 

**Expected behavior**
I would expect a drop-down with the possible values

**Comment by dbeuchler** [comment]
@mmarkwort as the major developer of the web based entry editor, do you have a quick idea to fix this?

**Comment by mmarkwort** [comment]
No, I need to check the bug. Assign the issue to me, please
