### ISSUE TITLE
CORS issue with auto configured service

### ISSUE THREAD

**Issue by dbeuchler** [PHOENIXCONTACT/MORYX-MaintenanceWeb#26]
After the last change #24 i got CORS errors if I access the maintenance web set by localhost. The server is configured for my hostname but before this was also possible. 

![image](https://user-images.githubusercontent.com/920832/98228823-6ca16900-1f59-11eb-9d3a-fcfa5bba617c.png)

**Comment by Toxantron** [comment]
Chrome network headers show that the server responds with CORS headers, which makes this more confusing.
