### ISSUE TITLE
Rename clone to prototype

### ISSUE THREAD

**Issue by slawor** [PHOENIXCONTACT/MORYX-MaintenanceWeb#5]
The Maintenance uses also the _entry concept_ from the [MORYX-Platform](https://github.com/PHOENIXCONTACT/MORYX-Platform/blob/dev/docs/articles/Platform/Serialization/EntryFormat.md) but instead of _prototype_ the name _clone_ was chosen. Same names will help to understand the implementation of the _entry concept_.

**Comment by Toxantron** [comment]
Closed by #37
